FROM golang:1.24-alpine AS builder

WORKDIR /build

# Копируем go.mod и go.sum
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Обновляем зависимости и собираем бинарник
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o radius-server ./cmd/radius-server

# Финальный образ
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

COPY --from=builder /build/radius-server .

EXPOSE 1812/udp

CMD ["./radius-server"]
